# This file serves as the core template for #
# all challenge-specific configurations.    #
# ----------------------------------------- #
# It holds all challenge related properties #
# for web handlers or other instances in a  #
# 'challenge.properties' file.              #

# Identity
challenge.name=Challenge name
challenge.scripts=A js-script or else leave empty
challenge.subtitle=Subtitle
challenge.difficulty=Difficulties: easy,       medium,             hard,           expert
challenge.difficultyColor=#2E7D32 (green), #EF6C00 (orange), #C62828 (red), #6A1B9A (purple)
challenge.objective=Objective, if more lines separate with "\"

# challenge hints
challenge.hint.1=hint 1<br>
challenge.hint.2=hint 2<br>
challenge.hint.3=hint 3

# From here on other challenge related properties such as route,
# challenge flag, db initializer and so on could be persisted.
# Configration.java has access to all entries in a method returning
# properties as a Map<String,String>

# Web | Flag | Challenge Hints | Messages | Reward | Database