# Identity
challenge.name=Login SQL Injection
challenge.difficulty=easy

# Flag
challenge.flag=ctf{That_Was_Easy_For_You}
challenge.message.invalid=Invalid credentials.

# Web
challenge.route=/login

# Database
challenge.initialize=login
challenge.table=login_users
challenge.db.allow_multi_queries=false