server.port=8080
server.stop.delay=1
server.execute.threads=10

database.url.prod=jdbc:postgresql://db:5432/vulnarebelapp
database.url.dev=jdbc:postgresql://localhost:5432/vulnarebelapp
database.user=postgres
database.pass=postgres
database.retry.max=30
database.retry.delay=2000

logging.level=INFO
logging.filename.databasemanager=database-logs
logging.filename.appserver=appserver-logs

web.static.path=/static

challenge.default=login