# Identity
challenge.name=Stored XSS
challenge.scripts=
challenge.subtitle=Can you guess the right message to retrieve the flag?
challenge.difficulty=Medium
challenge.difficultyColor=#EF6C00
challenge.objective=Execute JavaScript by abusing reflected user input.

# challenge hints
challenge.hint.1=Your comment is stored and displayed again every time the page is opened.<br>\
What happens if the browser interprets your input as HTML instead of plain text?<br>
challenge.hint.2= Once your JavaScript executes, it has access to the same browser environment \
as the rest of the application.<br> Besides the page itself, what other information does the browser store?<br>
challenge.hint.3=Open your browser's Developer Tools and inspect the application.<br> \
Pay attention to the <strong>Cookies</strong> section.<br> If JavaScript can read a cookie, so can an injected payload through

#web
challenge.route=/storedxss

# Reward
challenge.flag=ctf{Stored_Malicious_Payload}

# Messages
challenge.message.success=Congratulations! Challenge solved.
challenge.message.failure=Nothing interesting happened.

# Database
challenge.initialize=storedxss
challenge.db.allow_multi_queries=false