# Identity
challenge.name=Stored XSS
challenge.difficulty=middle

# Goal
challenge.description=Execute JavaScript by abusing reflected user input.

#web
challenge.route=/storedxss

# Reward
challenge.flag=ctf{Stored_Malicious_Payload}

# Messages
challenge.message.success=Congratulations! Challenge solved.
challenge.message.failure=Nothing interesting happened.

# Database
challenge.initialize=storedxss
challenge.db.allow_multi_queries=false