# Identity
challenge.name=Explorer
challenge.difficulty=medium

# Flag
challenge.flag=ctf{Let_The_Challenges_Begin}

#web
challenge.route=/
challenge.route.submit=/flag
challenge.route.resource=/resources/recon
challenge.redirect=/challenges

