# Identity
challenge.name=Union Based SQL Injection
challenge.difficulty=medium

# Flag related
challenge.message.invalid=Invalid credentials.

# Web
challenge.route=/union-sql-injection
challenge.htmlPlaceholder={{products}}

# Database
challenge.initialize=unionbasedsqli
challenge.table=products
challenge.table.secret=application_settings
challenge.db.allow_multi_queries=false