# Identity
challenge.name=Blind SQLi
challenge.difficulty=medium

# Flag
challenge.flag=ctf{Bl1nD_Bu7_N0t_D34f}

#web
challenge.route=/blindsqli
challenge.route.submit=/blindsqli/submit

# Database
challenge.initialize=blindsqli
challenge.table=blind_users
challenge.db.allow_multi_queries=false