@startuml
left to right direction
skinparam linetype ortho
skinparam groupInheritance 2
skinparam packageStyle rectangle

skinparam roundCorner 12

package core #81C784{
    class Application {
    	{field} {static} -LOG : Logger
    	{method} +start () : void
    	{method} +stop () : void
    }

    class Main {
    	{method}  {static} +main ( args : String[] ) : void
    }
}


package config #64B5F6{
    class Configuration {
    	{field} -properties : Properties
    	{method} +entries () : Map
    	{method} +getBoolean ( key : String ) : boolean
    	{method} +getInt ( key : String ) : int
    	{method} +getString ( key : String ) : String
    }


    class ConfigurationLoader {
    	{method}  {static} +load ( ConfigurationLoader : String ) : Configuration

    }
}


package database #A1887F{
    class DatabaseManager {
    	{field} {static} -LOGGER : Logger
    	{method} +getConnection () : Connection
    }

    class SchemaInitializer {
    	{method} -executeSqlFile ( conn : Connection , path : String ) : void
    	{method} +initialize ( challengeName : String ) : void
    }
}


package challenge #EF9A9A{
    abstract class Challenge {
    	{method} +articleCard () : Optional
    	{method} +config () : Configuration
    	{method} +initialize () : void
    	{method}  {abstract} +routes () : List
    }

    class ChallengesHandler {
    	{method} #doGet ( exchange : HttpExchange ) : void
    }

    package challenge.loginsqli #E57373{
        class LoginSqliChallenge {
        	{method} +articleCard () : Optional
        	{method} +initialize () : void
        	{method} +routes () : List
        }

        class LoginSqliHandler {
        	{method} #doGet ( exchange : HttpExchange ) : void
        	{method} #doPost ( exchange : HttpExchange ) : void
        }

        class LoginSqliService {
        	{method} +attemptLogin ( username : String , password : String ) : boolean
        }
    }

    package challenge.reflectedxss #BA68C8{
        class ReflectedXssChallenge {
        	{method} +articleCard () : Optional
        	{method} +routes () : List
        }


        class ReflectedXssHandler {
        	{method} #doGet ( exchange : HttpExchange ) : void
        }
    }
    package challenge.reconnaissance #4DB6AC{
        class ReconnaissanceChallenge {
        	{method} +articleCard () : Optional
        	{method} +routes () : List
        }


        class ReconnaissanceHandler {
        	{method} #doGet ( exchange : HttpExchange ) : void
        }


        class ReconnaissanceSubmitHandler {
        	{method} #doPost ( exchange : HttpExchange ) : void
        }
    }

    package challenge.storedxss #9575CD{
        class GuestbookEntry {
        	{field} -author : String
        	{field} -message : String
        	{method} +author () : String
        	{method} +message () : String
        }
        class StoredXssChallenge {
        	{method} +articleCard () : Optional
        	{method} +initialize () : void
        	{method} +routes () : List
        }


        class StoredXssHandler {
        	{method} #doGet ( exchange : HttpExchange ) : void
        	{method} #doPost ( exchange : HttpExchange ) : void
        }


        class StoredXssService {
        	{method} +getComments () : List
        	{method} +saveMessage ( author : String , message : String ) : void
        }
    }

    package challenge.unionsqli #FFB74D{
        class Product {
        	{field} -category : String
        	{field} -description : String
        	{field} -name : String
        	{field} -price : int
        	{method} +category () : String
        	{method} +description () : String
        	{method} +name () : String
        	{method} +price () : int
        }
        class UnionSqliChallenge {
        	{method} +articleCard () : Optional
        	{method} +initialize () : void
        	{method} +routes () : List
        }


        class UnionSqliHandler {
        	{method} #doGet ( exchange : HttpExchange ) : void
        	{method} #doPost ( exchange : HttpExchange ) : void
        }


        class UnionSqliService {
        	{method} +search ( input : String ) : List
        }
    }



    package challenge.blindsqli #FF8A65{
        class BlindSqliChallenge {
        	{method} +articleCard () : Optional
        	{method} +initialize () : void
        	{method} +routes () : List
        }


        class BlindSqliHandler {
        	{method} #doGet ( exchange : HttpExchange ) : void
        	{method} #doPost ( exchange : HttpExchange ) : void
        }


        class BlindSqliService {
        	{method} +searchAttempt ( search : String ) : boolean
        }


        class BlindSqliSubmitHandler {
        	{method} #doPost ( exchange : HttpExchange ) : void
        }
    }
}

package article #FFF176{
    class ArticleCard {
    	{field} -description : String
    	{field} -route : String
    	{field} -title : String
    	{method} +description () : String
    	{method} +route () : String
    	{method} +title () : String
    }

    class ResourceHandler {
    	{method} #doGet ( exchange : HttpExchange ) : void
    }

    class ResourceIndexHandler {
    	{method} -buildCards () : String
    	{method} #doGet ( exchange : HttpExchange ) : void
    }
}

package html #CFD8DC{
    class html.TemplateRenderer {
        {method} +render ( html : byte[] ) : String
    	{method} +render ( template : byte[] , content : byte[] ) : String
    }
}



package http #90CAF9{

    abstract class BaseHandler {
    	{field} {static} -LOGGER : Logger
    	{field} {static} #TEXT_HTML : String
    	{field} {static} #TEXT_PLAIN : String
    	{method} #doGet ( exchange : HttpExchange ) : void
    	{method} #doPost ( exchange : HttpExchange ) : void
    	{method} +handle ( exchange : HttpExchange ) : void
    	{method} #parseUrlEncodedData ( body : String ) : Map
    	{method} #readBody ( exchange : HttpExchange ) : String
    	{method} #readResource ( classPath : String ) : byte[]
    	{method} #sendResponse ( exchange : HttpExchange , statusCode : int , contentType : String , body: String ) : void
    	{method} #sendResponse ( exchange : HttpExchange , statusCode : int , contentType : String , body : byte[] ) : void

    }

    class VulnaHttpServer {
    	{field} {static} -LOGGER : Logger
    	{field} -delay : int
    	{field} -server : HttpServer
    	{method} +addContext ( path : String , handler : HttpHandler ) : void
    	{method} +applyRoutes ( router : Router ) : void
    	{method} +start () : void
    	{method} +stop () : void
    }

    class Route {
    	{field} -handler : HttpHandler
    	{field} -path : String
    }


    class Router {
    	{method} +register ( route : Route ) : void
    }
}

Application *--  Router : router
Application *--  VulnaHttpServer : server
BlindSqliChallenge *--  Configuration : articleConfig
BlindSqliChallenge *--  DatabaseManager : manager
BlindSqliChallenge --|>  Challenge
BlindSqliHandler *--  BlindSqliService : service
BlindSqliHandler *--  Configuration : challengeConfig
BlindSqliHandler *--  TemplateRenderer : renderer
BlindSqliHandler --|>  BaseHandler
BlindSqliService *--  DatabaseManager : manager
BlindSqliSubmitHandler *--  Configuration : challengeConfig
BlindSqliSubmitHandler --|>  BaseHandler
Challenge *--  Configuration : config
ChallengesHandler --|>  BaseHandler
DatabaseManager *--  Configuration : config
LoginSqliChallenge *--  Configuration : articleConfig
LoginSqliChallenge *--  DatabaseManager : manager
LoginSqliChallenge --|>  Challenge
LoginSqliHandler *--  Configuration : challengeConfig
LoginSqliHandler *--  LoginSqliService : service
LoginSqliHandler *--  TemplateRenderer : renderer
LoginSqliHandler --|>  BaseHandler
LoginSqliService *--  DatabaseManager : manager
ReconnaissanceChallenge *--  Configuration : articleConfig
ReconnaissanceChallenge --|>  Challenge
ReconnaissanceHandler --|>  BaseHandler
ReconnaissanceSubmitHandler *--  Configuration : challengeConfig
ReconnaissanceSubmitHandler --|>  BaseHandler
ReflectedXssChallenge *--  Configuration : articleConfig
ReflectedXssChallenge --|>  Challenge
ReflectedXssHandler *--  TemplateRenderer : renderer
ReflectedXssHandler --|>  BaseHandler
ResourceHandler *--  TemplateRenderer : renderer
ResourceHandler --|>  BaseHandler
ResourceIndexHandler "1" o-- "0..*"  ArticleCard : cards
ResourceIndexHandler --|>  BaseHandler
Router "1" o-- "0..*"  Route : routes
SchemaInitializer *--  DatabaseManager : manager
StoredXssChallenge *--  Configuration : articleConfig
StoredXssChallenge *--  DatabaseManager : manager
StoredXssChallenge --|>  Challenge
StoredXssHandler *--  Configuration : challengeConfig
StoredXssHandler *--  StoredXssService : service
StoredXssHandler *--  TemplateRenderer : renderer
StoredXssHandler --|>  BaseHandler
StoredXssService *--  DatabaseManager : manager
TemplateRenderer *--  Configuration : config
UnionSqliChallenge *--  Configuration : articleConfig
UnionSqliChallenge *--  DatabaseManager : manager
UnionSqliChallenge --|>  Challenge
UnionSqliHandler *--  Configuration : challengeConfig
UnionSqliHandler *--  TemplateRenderer : renderer
UnionSqliHandler *--  UnionSqliService : service
UnionSqliHandler --|>  BaseHandler
UnionSqliService *--  DatabaseManager : manager


@enduml