# Identity
challenge.name=Reflected XSS
challenge.difficulty=easy

# Goal
challenge.description=Execute JavaScript by abusing reflected user input.

#web
challenge.route=/reflectedxss

# Reward
challenge.flag=ctf{Reflected_XSS_Master}

# Messages
challenge.message.success=Congratulations! Challenge solved.
challenge.message.failure=Nothing interesting happened.